pub const NEGATIVE_TOTAL_VALUE: felt252 = 'NEGATIVE_TOTAL_VALUE';
pub const ONLY_PERPS_CAN_DEPOSIT: felt252 = 'ONLY_PERPS_CAN_DEPOSIT';
pub const ONLY_PERPS_CAN_RECEIVE: felt252 = 'ONLY_PERPS_CAN_RECEIVE';
pub const ONLY_PERPS_CAN_WITHDRAW: felt252 = 'ONLY_PERPS_CAN_WITHDRAW';
