name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.45.0"

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.4"


      - name: Run test and coverage
        working-directory: ./
        run: scarb test -w

      - name: Check formatting
        run: |
          scarb fmt -w --check

      - name: Build Contracts
        run: |
          scarb build