name: CI

on:
  pull_request:

jobs:
  cairo_tests:
    runs-on: namespace-profile-starkware-libs-starknet-perpetual-xlarge-hm-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@v4

      # -------------------------------
      # Install Starknet Foundry NIGHTLY
      # -------------------------------
      - name: Install Starknet Foundry (nightly)
        env:
          TAG: nightly-2026-02-03
          GH_REPO: software-mansion-labs/starknet-foundry-nightlies
        run: |
          set -euo pipefail

          sudo apt-get update
          sudo apt-get install -y jq

          release_json="$(curl -sL "https://api.github.com/repos/${GH_REPO}/releases/tags/${TAG}")"

          url="$(echo "$release_json" \
            | jq -r '.assets[].browser_download_url' \
            | grep -E 'linux.*(x86_64|amd64).*\.tar\.gz$' \
            | head -n 1)"

          if [ -z "$url" ]; then
            echo "Could not find nightly asset"
            echo "$release_json" | jq -r '.assets[].name'
            exit 1
          fi

          curl -L "$url" -o snfoundry.tar.gz
          mkdir -p "$HOME/.snfoundry"
          tar -xzf snfoundry.tar.gz -C "$HOME/.snfoundry"
          echo "$HOME/.snfoundry/bin" >> "$GITHUB_PATH"

          snforge --version
          sncast --version

      # -------------------------------
      # Scarb
      # -------------------------------
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.15.1"

      - name: Build Contracts
        run: scarb build

      - name: Install cairo-coverage
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Run test and coverage
        run: scarb test -w --coverage

      - name: Check formatting
        run: scarb fmt -w --check

  python_tests:
    runs-on: namespace-profile-starkware-libs-starknet-perpetual-xlarge-hm-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@v4

      - name: Install asdf
        run: scripts/install_asdf.sh

      - name: Install starknet-devnet
        run: |
          asdf plugin add starknet-devnet
          asdf install starknet-devnet 0.7.2
          asdf global starknet-devnet 0.7.2

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.15.1"

      - name: Build Contracts
        run: scarb --release build

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Run Python Tests
        run: scripts/python_tests.sh
